name = "bookmarks"
compatibility_date = "2024-09-25"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "bookmarks"
database_id = "a89f7b6e-93af-4c6a-9a0b-5a111dc18f27"

[vars]
# 访问密码，部署后可通过 CF Dashboard 修改
ACCESS_PASSWORD = "shaduanduan123"
